import {Game} from './engine.mjs';
import {chooseMove} from './ai.mjs';
import {boardTargets,selectBoardTarget,sourceMoves} from './selection.mjs';
const root=document.querySelector('#app'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let pool,doc,g,view=0,mode='bot',busy=false,curtain=false,source=null,picks=null,step='target',replace=new Set(),error='';
const rules=`Five Character slots. No blocking. Attack the opposing Leader or a Rotated Character; Ready Characters are protected from normal attacks. Character combat deals damage simultaneously, without overflow. New Characters wait until your next Turn to attack unless Hothead. Once per Turn, Stash a hand card; Ready Stash pays Costs. Full Turns are a provisional baseline. Automatic triggers are free and can cascade. Trench Coat stores an unstacked friendly Character under another; the host gets +1/+1 per card. Stored cards have no abilities or slots and are discarded when the host leaves. Only the host is Defeated. Responses: one opportunity after an Attack, defender first, then attacker if defender passes.`;
function setup(){root.innerHTML=`<section class="setup"><span class="eyebrow">UNHINGED / EXPERIMENT 02</span><h1>Room for five.<br>Room for trouble.</h1><p class="intro">Attack. Preserve an engine. Stack the guest list.<br>A separate lab for exposed combat and scarce board space.</p><div class="settings">${['Your deck','Opponent deck'].map((label,i)=>`<label>${label}<select id="deck${i}">${doc.decks.map((d,j)=>`<option value="${j}" ${j===i?'selected':''}>${esc(d.leader)}</option>`).join('')}</select></label>`).join('')}<label>Play mode<select id="mode"><option value="bot">Against bot</option><option value="local">Local two-player</option></select></label></div><button id="start" class="primary">Take your seat →</button><details><summary>Experimental rules</summary><p>${rules}</p></details><p class="muted">TESTING · 25 Health · 40-card decks · full Turns, provisionally</p><nav><a href="../../web/">Carl 0.3</a><a href="../schemes/">Scheme Lab</a><a href="https://github.com/jobeck17/unhinged/tree/main/lab/board-width">Lab rules & source</a></nav></section>`;root.querySelector('#start').onclick=()=>{mode=root.querySelector('#mode').value;g=new Game(pool,doc,[+root.querySelector('#deck0').value,+root.querySelector('#deck1').value]);window.game=g;view=0;curtain=mode==='local';render();};}
function validTarget(uid){return picks&&boardTargets(picks,step).includes(uid)}
function card(x,p,zone,index){const c=g.card(x),b=zone==='board',selected=b?source?.uid===x.uid:source?.index===index,target=b&&validTarget(x.uid),char=c.type==='Character';return `<button class="card ${b&&!x.ready?'rotated':''} ${selected?'selected':''} ${target?'target':''} ${!b&&replace.has(index)?'selected':''}" data-zone="${zone}" data-p="${p}" data-index="${index??''}" data-uid="${x.uid??''}" ${p!==view&&!b?'disabled':''}><span class="card-top"><span>${esc(c.type)}</span><b>${b?x.ready?'READY':'ROTATED':'COST '+c.cost}</b></span><strong>${esc(c.name)}</strong><span class="card-text">${esc(c.text)}</span>${char?`<span class="stats"><span><small>POWER</small>${b?g.power(x):c.power}</span><span><small>${b?'GUARD LEFT':'GUARD'}</small>${b?g.remaining(x):c.guard}</span></span>`:''}<span class="card-foot">${target?'◎ SELECT TARGET':b?x.stored?.length?'STACKED · '+x.stored.map(id=>g.card(id).name).join(', '):char&&x.born>=g.players[p].turns?'NEW THIS TURN':x.damage?x.damage+' damage marked':'IN PLAY':'TAP FOR ACTIONS'}</span></button>`}
function row(p){const s=g.players[p],l=g.leader(p);return `<section class="battle-row ${p===view?'own':'opponent'}" aria-label="${p===view?'Your':'Opponent'} battlefield"><button class="leader ${p!==view&&validTarget(-1)?'target':''}" data-leader="${p}"><span class="eyebrow">${p===view?'YOU':'OPPONENT'} · LEADER</span><strong>${esc(l.name)}</strong><span class="health">${s.hp}<small>HEALTH</small></span><span class="leader-info">${g.chars(p).length}/${g.rules.maxCharacters} Characters<br>${g.fuel(p)}/${s.stash.length} Ready Stash<br>Deck ${s.deck.length} · Hand ${s.hand.length}</span><span class="card-foot">${p!==view&&validTarget(-1)?'◎ SELECT TARGET':'NO BLOCKING'}</span></button><div class="slots">${g.chars(p).map(x=>card(x,p,'board')).join('')}${Array.from({length:Math.max(0,g.rules.maxCharacters-g.chars(p).length)},(_,i)=>`<div class="empty-slot"><span>+<small>OPEN SLOT ${g.chars(p).length+i+1}</small></span></div>`).join('')}</div></section>`}
function moveLabel(m){if(m.type==='end')return'End Turn';if(m.type==='passResponse')return'Pass Response';if(m.type==='stash')return'Stash';if(m.type==='attack')return'Attack';if(m.type==='play'||m.type==='respond')return m.type==='respond'?'Play Response':'Play';if(m.type==='discard')return'Discard';if(m.type==='choose')return String(m.value??'Skip');return m.type;}
function render(){if(!g)return setup();if(curtain){root.innerHTML=`<section class="setup"><span class="eyebrow">LOCAL TWO-PLAYER</span><h1>Pass to Player ${g.actor+1}.</h1><p>${esc(g.name(g.actor))} has a decision.</p><button id="reveal" class="primary">Reveal my hand</button></section>`;root.querySelector('#reveal').onclick=()=>{view=g.actor;curtain=false;render()};return;}
 const can=!busy&&g.actor===view&&g.winner===null;
 const moves=source&&can?sourceMoves(g,source):[];
 const instruction=picks?step==='second'?'Choose the host on your board.':picks[0]?.second!==undefined?'Choose the Character to store under a host.':'Choose a highlighted target on the board.':g.winner!==null?g.name(g.winner)+' wins · '+g.endReason:busy?'Bot is thinking…':g.phase==='response'?g.name(g.actor)+' may play one Response.':g.phase==='mulligan'?'Select hand cards to replace, or keep your hand.':'Select a Character to attack, or a hand card to play / Stash.';
 root.innerHTML=`<header><div><b class="brand">UNHINGED.</b><span class="eyebrow">BOARD WIDTH LAB · TESTING · ROUND ${g.round}</span></div><button id="new">New match</button></header><section class="controls"><div><span class="eyebrow">${esc(g.name(g.actor))} · ${esc(g.phase)}</span><p id="instruction" role="status">${esc(instruction)}</p>${g.pending?`<p class="combat-note">${esc(g.card(g.obj(g.pending.attacker)).name)} → ${g.pending.target===-1?esc(g.name(1-g.turn)):esc(g.card(g.obj(g.pending.target)).name)} · awaiting Response</p>`:''}</div><div class="actions">${picks?'<button id="cancel">Cancel selection</button>':can&&source?[...new Set(moves.map(m=>m.type))].map(type=>`<button data-action="${type}">${moveLabel({type})}</button>`).join(''):''}${can&&g.phase==='main'?'<button id="end" class="primary">End Turn</button>':''}${can&&g.phase==='response'?'<button id="pass">Pass Response</button>':''}${can&&g.phase==='mulligan'?`<button id="keep" class="primary">${replace.size?'Replace '+replace.size:'Keep hand'}</button>`:''}</div></section>${error?`<p role="alert">${esc(error)}</p>`:''}<p class="scroll-hint">Swipe the battlefield sideways to see all five slots.</p><div class="battlefield">${row(1-view)}${row(view)}</div><section class="hand"><div class="section-head"><h2>Your hand <small>${g.players[view].hand.length} cards</small></h2><span>Stash ${g.fuel(view)}/${g.players[view].stash.length} Ready</span></div><div class="hand-cards">${g.players[view].hand.map((id,i)=>card({id},view,'hand',i)).join('')}</div></section><div class="lower"><details><summary>Rules & testing assumptions</summary><p>${rules}</p></details><details open><summary>Recent events</summary>${g.log.slice(0,8).map(s=>`<p>${esc(s)}</p>`).join('')}</details></div>`;
 root.querySelector('#new').onclick=()=>{if(busy)return;g=null;source=null;picks=null;replace.clear();setup()};root.querySelector('#end')?.addEventListener('click',()=>act({type:'end'}));root.querySelector('#pass')?.addEventListener('click',()=>act({type:'passResponse'}));root.querySelector('#keep')?.addEventListener('click',()=>act({type:'mulligan',indices:[...replace]}));root.querySelector('#cancel')?.addEventListener('click',()=>{picks=null;source=null;render()});
 root.querySelectorAll('[data-leader]').forEach(b=>b.onclick=()=>{if(can&&+b.dataset.leader!==view)pick(-1)});
 root.querySelectorAll('[data-zone]').forEach(b=>b.onclick=()=>{if(!can)return;const board=b.dataset.zone==='board',index=+b.dataset.index,uid=+b.dataset.uid;if(board&&picks)return pick(uid);if(+b.dataset.p!==view)return;if(!board&&g.phase==='mulligan'){replace.has(index)?replace.delete(index):replace.add(index);render();return;}if(!board&&g.phase==='discard')return act({type:'discard',index});source=board?{uid}:{index};picks=null;render()});
 root.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>begin(moves.filter(m=>m.type===b.dataset.action)));
 if(can&&g.phase==='choose'){const box=document.createElement('section');box.className='controls';g.legalMoves().forEach(m=>{const b=document.createElement('button');b.textContent=moveLabel(m);b.onclick=()=>act(m);box.append(b)});root.append(box)}
}
function begin(moves){if(!moves.length)return;if(moves.some(m=>Number.isInteger(m.target))){picks=moves;step='target';render()}else act(moves[0]);}
function pick(uid){if(!picks)return;const matches=selectBoardTarget(picks,uid,step);if(!matches.length)return;if(step==='target'&&matches.some(m=>m.second!==undefined)){picks=matches;step='second';render()}else act(matches[0]);}
async function act(m){if(busy)return;try{g.apply(m);source=null;picks=null;replace.clear();error='';if(mode==='local'){curtain=g.actor!==view&&g.winner===null;render();return;}busy=true;render();while(g.actor===1&&g.winner===null){await new Promise(r=>setTimeout(r,90));g.apply(chooseMove(g));render()}busy=false;render();}catch(e){busy=false;error=e.message;console.error(e);render()}}
window.addEventListener('keydown',e=>{if(e.key==='Escape'){picks=null;source=null;render()}});
try{[pool,doc]=await Promise.all(['CARDS.json','DECKS.json'].map(async f=>{const r=await fetch(f);if(!r.ok)throw Error('Unable to load '+f);return r.json()}));setup()}catch(e){root.textContent=e.message;console.error(e)}
