import {Game,LEADERS} from './engine.js';
import {aiAction,aiChoice} from './ai.js';
const root=document.querySelector('#app');let pool,decks,game,human=0,modal=null,busy=false,phase='setup',mulligan=0,selected=new Set(),recent=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
try{[pool,decks]=await Promise.all([fetch('../production/cards/cards.json').then(r=>{if(!r.ok)throw Error('Card data unavailable');return r.json()}),fetch('../production/playtests/florida-vs-hoa/decks.json').then(r=>{if(!r.ok)throw Error('Deck data unavailable');return r.json()})]);if(pool.version!==decks.card_pool)throw Error('Deck and card pool versions differ');render()}catch(e){root.innerHTML=`<div class="setup"><h1>Can’t load the game</h1><p>${esc(e.message)}. Open the app through GitHub Pages or a local web server.</p></div>`}
function render(){if(!pool)return;if(phase==='setup'){root.innerHTML=`<div class="setup"><div class="small">Unhinged · Donut 0.1</div><h1>Play the<br>problem.</h1><p>Choose your Leader. The other deck plays itself. Both decks use the current 40-card Florida Man versus HOA President test lists.</p><div class="options"><button class="option reckless" data-start="0">Florida Man <span>Reckless + Expendable · risk, self-damage, dice</span></button><button class="option stonewall" data-start="1">HOA President <span>Stonewall + Salvage · blockers, healing, Charge</span></button></div><p class="muted">Single player · no account · no card art · tap any card to read it</p></div>`;root.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>start(+b.dataset.start));return}
 if(phase==='mulligan'){let s=game.players[human];root.innerHTML=`<div class="top"><span class="brand">UNHINGED</span><span class="pill">Mulligan</span></div><div class="setup"><div class="small">${esc(decks.decks[human].leader)}</div><h1>Keep or replace?</h1><p>Tap cards to select replacements. Draw that many cards, then shuffle the selected cards back. The AI has already prepared its opening hand.</p><div class="lane">${s.hand.map((id,i)=>cardHTML({id},'hand',human,i,selected.has(i))).join('')}</div><button id="keep" class="primary" style="margin-top:20px">${selected.size?'Replace '+selected.size+' and start':'Keep hand and start'}</button></div>`;wireCards();root.querySelector('#keep').onclick=async()=>{await game.mulligan(human,[...selected]);selected.clear();game.begin();phase='playing';render();await aiTurn()};return}
 let ai=1-human,active=game.turn===human&&!busy&&game.winner===null;
 root.innerHTML=`<div class="top"><span class="brand">UNHINGED<span style="color:#ed9360">.</span></span><span class="pill">Round ${game.round} · ${game.winner!==null?esc(decks.decks[game.winner].leader)+' wins':game.turn===human?'Your turn':'AI turn'}</span></div>
 <div class="board"><div class="side">${headHTML(ai,false)}<div class="section"><div class="sectionhead">Opponent’s board <span>${game.chars(ai).length} Characters</span></div><div class="lane">${game.chars(ai).map(x=>cardHTML(x,'board',ai)).join('')||'<span class="empty">No Characters</span>'}</div>${itemsHTML(ai)}</div></div>
 <div class="side">${headHTML(human,true)}<div class="section"><div class="sectionhead">Your board <span>${game.chars(human).length} Characters</span></div><div class="lane">${game.chars(human).map(x=>cardHTML(x,'board',human)).join('')||'<span class="empty">No Characters</span>'}</div>${itemsHTML(human)}</div><div class="section hand"><div class="sectionhead">Your hand <span>${game.players[human].hand.length} cards</span></div><div class="lane">${game.players[human].hand.map((id,i)=>cardHTML({id},'hand',human,i)).join('')||'<span class="empty">No cards</span>'}</div></div></div></div>
 <div class="controls"><span class="status">${game.winner!==null?'Game over':busy?'Resolving…':active?'Tap a card to read or act':'Opponent is thinking…'}</span><div style="display:flex;gap:7px">${game.winner!==null?'<button id="new" class="primary">New game</button>':`<button id="pass" class="ghost" ${active?'':'disabled'}>Pass turn</button>`}</div></div>
 <section class="log"><h3>Game log</h3>${game.log.slice(0,12).map(x=>`<p>${esc(x)}</p>`).join('')}</section><p class="help">Tap a card for full text and available actions. Rotated cards carry a sideways marker. Attack targets and blockers are chosen during the Attack. Card text and rules are experimental.</p>`;
 wireCards();root.querySelectorAll('[data-leader]').forEach(b=>b.onclick=()=>showCard({leader:+b.dataset.leader}));let pass=root.querySelector('#pass');if(pass)pass.onclick=()=>humanAction(()=>game.pass());let nw=root.querySelector('#new');if(nw)nw.onclick=()=>{phase='setup';game=null;render()};if(modal)showModal(modal)}
function headHTML(p,you){let s=game.players[p];return `<div class="head ${you?'you':''}"><div class="line"><div class="leader ${s.ready?'':'rotated'}" role="button" tabindex="0" data-leader="${p}"><span class="small">${you?'You':'AI'} · ${esc(LEADERS[p].style)}</span><br><strong>${esc(LEADERS[p].name)} ${s.ready?'':'↷'}</strong></div><b style="font-size:1.5rem;color:${s.hp<10?'#ffa99d':'#ebd9ab'}">♥ ${s.hp}</b></div><div class="metrics"><span>Fuel ${s.fuel}/${Math.min(game.round,7)}</span><span>Charge ${s.charge}/3</span><span>Deck ${s.deck.length}</span><span>Hand ${you?s.hand.length:'?'} </span><span>${s.ready?'Ready':'Rotated · Vulnerable'}</span></div></div>`}
function itemsHTML(p){let items=game.players[p].board.filter(x=>game.card(x).type==='Item');return items.length?`<div class="sectionhead" style="margin-top:12px">Items</div><div class="lane" style="min-height:132px">${items.map(x=>cardHTML(x,'board',p)).join('')}</div>`:''}
function cardHTML(x,zone,p,index,chosen=false){let c=game.card(x),onBoard=zone==='board',char=c.type==='Character',rot=onBoard&&!x.ready,stats=onBoard&&char?`${game.power(x)} ⚔ · ${game.guard(x)} ⛨`:char?`${c.power} ⚔ · ${c.guard} ⛨`:c.type;return `<button type="button" class="card ${c.style.toLowerCase()} ${rot?'rotated':''} ${chosen?'targeted':''} ${game.pendingAttack?.attacker===x.uid?'attacking':''} ${game.pendingAttack?.target===x.uid?'targeted':''}" data-zone="${zone}" data-player="${p}" data-uid="${x.uid||''}" data-index="${index??''}" aria-label="${esc(c.name)}, ${esc(stats)}${rot?', Rotated':''}"><span class="tag">${esc(c.style)} · ${onBoard&&rot?'↷ ROTATED':c.cost+' FUEL'}</span><b>${esc(c.name)}</b><span class="summary">${esc(c.text||c.flavor||'Character')}</span><span class="numbers"><span>${esc(stats)}</span>${onBoard&&char&&x.damage?`<span class="damage">♥ −${x.damage}</span>`:''}</span></button>`}
function wireCards(){root.querySelectorAll('.card').forEach(b=>b.onclick=()=>{if(phase==='mulligan'){let i=+b.dataset.index;selected.has(i)?selected.delete(i):selected.add(i);render();return}let {zone,player,uid,index}=b.dataset;if(zone==='hand')showCard({id:game.players[human].hand[+index],handIndex:+index});else showCard({uid:+uid})})}
function showCard(ref){if(!game)return;let leader=ref.leader!==undefined,p=leader?ref.leader:null,x=leader?null:ref.uid?game.obj(ref.uid):null,c=leader?null:game.card(x||ref.id);if(!leader&&!c)return;
 let me=game.turn===human&&!busy&&game.winner===null;let own=x?.owner===human;let canPlay=ref.handIndex!==undefined&&me&&c.cost<=game.players[human].fuel;let canAttack=x&&own&&c.type==='Character'&&me&&game.canAttack(x);let canAct=x&&own&&me&&game.canActivate(x)&&['P003','P165','P124','P132','P138','P147','P117','P179','P120','P027','P178'].includes(x.id);let canLead=leader&&p===human&&me&&game.players[p].ready;
 let buttons=`<button class="ghost" id="close">Close</button>${canPlay?'<button class="primary" id="playcard">Play card</button>':''}${canAttack?'<button class="primary" id="attack">Attack</button>':''}${canAct?'<button class="primary" id="activate">Activate</button>':''}${canLead?'<button class="primary" id="lead">Ability</button>':''}${canLead&&game.players[p].charge===3?'<button class="primary" id="ultimate">Ultimate</button>':''}`;
 let title=leader?LEADERS[p].name:c.name,description=leader?[LEADERS[p].passive,LEADERS[p].ability,LEADERS[p].charge,LEADERS[p].ultimate].join('\n\n'):c.text||c.flavor||'No special ability.',type=leader?`Leader · ${LEADERS[p].style}`:`${c.type} · ${c.style} · ${c.id}`,stats=leader?`<span>♥ ${game.players[p].hp}/25</span><span>Charge ${game.players[p].charge}/3</span><span>${game.players[p].ready?'Ready':'Rotated · Vulnerable'}</span>`:`<span>Cost ${c.cost}</span>${c.type==='Character'?`<span>⚔ ${x?game.power(x):c.power} Power</span><span>⛨ ${x?game.guard(x):c.guard} Guard</span>`:''}${x?`<span>${x.ready?'Ready':'Rotated'}</span>${x.damage?`<span>Damage ${x.damage}</span>`:''}`:''}`;
 modal={kind:'detail',html:`<div class="overlay" id="overlay"><article class="sheet" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="type">${esc(type)}</div><h2>${esc(title)}</h2><div class="stats">${stats}</div>${!leader&&c.traits.length?`<p class="muted">Traits: ${esc(c.traits.join(', '))}</p>`:''}<p class="rule">${esc(description)}</p>${x&&game.items(x).length?`<p class="muted">Attached: ${game.items(x).map(i=>esc(game.card(i).name)).join(', ')}</p>`:''}<div class="buttons">${buttons}</div></article></div>`};showModal(modal);let q=id=>document.getElementById(id);q('playcard')&&(q('playcard').onclick=()=>{close();humanAction(()=>game.play(ref.handIndex))});q('attack')&&(q('attack').onclick=()=>{close();humanAction(()=>game.attack(x.uid))});q('activate')&&(q('activate').onclick=()=>{close();humanAction(()=>game.activate(x.uid))});q('lead')&&(q('lead').onclick=()=>{close();humanAction(()=>game.leader(false))});q('ultimate')&&(q('ultimate').onclick=()=>{close();humanAction(()=>game.leader(true))})}
function showModal(entry){document.querySelector('.overlay')?.remove();if(!entry)return;document.body.insertAdjacentHTML('beforeend',entry.html);let overlay=document.querySelector('.overlay');overlay.onclick=e=>{if(e.target===overlay&&entry.kind==='detail')close()};overlay.querySelector('#close')?.addEventListener('click',close)}
function close(){modal=null;document.querySelector('.overlay')?.remove()}
async function ask(request){if(request.player!==human){let answer=aiChoice(game,request);return answer}return new Promise(resolve=>{let {title,options=[],multi,max,mandatory}=request;let checked=[];const html=`<div class="overlay"><div class="sheet" role="dialog" aria-modal="true"><div class="type">Choose an action</div><h2>${esc(title)}</h2>${request.attackContext ? '<div class="attack-context"><strong>ATTACKING: '+esc(request.attackContext.name)+' · '+esc(request.attackContext.power)+' Power</strong><span>Guard '+esc(request.attackContext.guard)+' · Damage '+esc(request.attackContext.damage)+'</span><p>'+esc(request.attackContext.text||'No special ability.')+'</p></div>' : ''}<p class="muted">${multi?'Tap in the order they should resolve. You can choose none.':'Tap one option to continue.'}</p>${options.map((o,i)=>`<button type="button" class="choice" data-choice="${i}">${esc(o.label)}</button>`).join('')}<div class="modal-actions">${mandatory?'':'<button id="cancel" class="ghost">Cancel</button>'}${multi?'<button id="done" class="primary">Confirm</button>':''}</div></div></div>`;modal={kind:'choice',html};showModal(modal);let finish=v=>{close();resolve(v)};document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{let i=+b.dataset.choice;if(!multi)finish(options[i].value);else{if(checked.includes(i)){checked=checked.filter(k=>k!==i);b.classList.remove('selected')}else if(!max||checked.length<max){checked.push(i);b.classList.add('selected')}document.querySelector('#done').textContent=`Confirm ${checked.length}`}});document.querySelector('#cancel')?.addEventListener('click',()=>finish(multi?[]:null));document.querySelector('#done')?.addEventListener('click',()=>finish(checked.map(i=>options[i].value)))})}
function start(p){human=p;game=new Game(pool,decks,ask,()=>{if(phase==='playing'&&!modal)render()});phase='mulligan';let ai=1-human;let keep=game.players[ai].hand.map((id,i)=>({id,i})).filter(x=>game.card(x.id).type==='Character'&&game.card(x.id).cost<=3).slice(0,3).map(x=>x.i);game.mulligan(ai,Array.from({length:7},(_,i)=>i).filter(i=>!keep.includes(i)));render()}
async function humanAction(fn){if(busy||game.turn!==human)return;busy=true;render();try{await fn()}catch(e){console.error(e);alert('This move could not finish: '+e.message)}finally{busy=false;render();await aiTurn()}}
async function aiTurn(){if(phase!=='playing'||!game||game.winner!==null||game.turn===human||busy)return;busy=true;render();let steps=0;try{while(game.turn!==human&&game.winner===null&&steps++<60){await new Promise(r=>setTimeout(r,260));let move=aiAction(game,game.turn);if(move.type==='pass')await game.pass();if(move.type==='attack')await game.attack(move.uid);if(move.type==='play')await game.play(move.index);if(move.type==='activate')await game.activate(move.uid);if(move.type==='leader')await game.leader(false);if(move.type==='ultimate')await game.leader(true);render()}if(steps>=60)throw Error('AI turn limit reached')}catch(e){console.error(e);alert('The AI stopped: '+e.message)}finally{busy=false;render()}}
