import {Game,LEADERS} from './engine.js?v=composure-01';
import {aiAction,aiChoice} from './ai.js?v=composure-01';
const root=document.querySelector('#app');
let pool,decks,game,human=0,phase='setup',busy=false,modal=null,selected=new Set();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mark=t=>t==='Character'?'♟':t==='Action'?'⚡':'⬢';
try{
 [pool,decks]=await Promise.all([
  fetch('./CARDS.json?v=composure-01').then(r=>r.json()),
  fetch('./DECKS.json?v=composure-01').then(r=>r.json())
 ]);
 if(pool.version!==decks.card_pool)throw Error('Lab card/deck versions do not match');
 render();
}catch(e){root.innerHTML='<div class="setup"><h1>Lab failed to load</h1><p>'+esc(e.message)+'</p></div>'}

function render(){
 if(phase==='setup'){
  const opts=decks.decks.map((d,i)=>'<option value="'+i+'">'+esc(d.leader)+' · '+esc(d.styles[0])+'</option>').join('');
  root.innerHTML='<div class="setup deck-setup"><div class="small">Unhinged · Composure Lab 0.1</div><h1>Drive them<br>Unhinged.</h1><p>Each Leader has <b>15 Composure</b>. Characters have <b>Power / Guard / Antics</b>. Attack Characters with Power, or Rotate a Character to <b>Cause Trouble</b> and make the opposing Leader lose its Antics in Composure. Ready Characters can Block Trouble. A Block stops all Antics and starts normal combat instead.</p><p><b>Five Characters max.</b> Everything else stays as close to Carl 0.3 as possible: Stash, full Turns, attack delay, damage, retaliation, Items and card text.</p><div class="deck-picker"><label>Your deck</label><select id="you" class="deck-select">'+opts+'</select></div><div class="deck-picker"><label>Opponent</label><select id="them" class="deck-select">'+opts+'</select></div><button id="start" class="primary deck-start">Start playtest</button><p class="muted">TESTING only. Antics values and converted Leader-facing effects are first-pass numbers.</p></div>';
  root.querySelector('#you').value='0';root.querySelector('#them').value='4';
  root.querySelector('#start').onclick=()=>start(+root.querySelector('#you').value,+root.querySelector('#them').value);
  return;
 }
 if(phase==='mulligan'){
  const s=game.players[human];
  root.innerHTML='<div class="top"><span class="brand">UNHINGED</span><span class="pill">Composure Lab · Mulligan</span></div><div class="setup"><h1>Keep or replace?</h1><p>Tap cards to replace, then start.</p><div class="lane">'+s.hand.map((id,i)=>cardHTML({id},'hand',human,i,selected.has(i))).join('')+'</div><button id="keep" class="primary" style="margin-top:20px">'+(selected.size?'Replace '+selected.size:'Keep hand')+'</button></div>';
  wireCards();
  root.querySelector('#keep').onclick=async()=>{await game.mulligan(human,[...selected]);selected.clear();game.begin();phase='playing';render();await aiTurn()};
  return;
 }
 const ai=1-human,active=game.turn===human&&!busy&&game.winner===null;
 root.innerHTML='<div class="top"><span class="brand">UNHINGED<span style="color:#ed9360">.</span></span><span class="pill">Round '+game.round+' · '+(game.winner!==null?esc(game.decks[game.winner].leader)+' wins':game.turn===human?'Your turn':'AI turn')+'</span></div>'+
 '<div class="board"><div class="side">'+head(ai,false)+section(ai,false)+'</div><div class="side">'+head(human,true)+section(human,true)+'<div class="section hand"><div class="sectionhead">Your hand <span>'+game.players[human].hand.length+' cards</span></div><div class="lane">'+(game.players[human].hand.map((id,i)=>cardHTML({id},'hand',human,i)).join('')||'<span class="empty">No cards</span>')+'</div></div></div></div>'+
 '<div class="controls"><span class="status">'+(game.winner!==null?'Game over':busy?'Resolving…':active?'Fight, Cause Trouble, or build your board':'Opponent is thinking…')+'</span>'+(game.winner!==null?'<button id="new" class="primary">New game</button>':'<button id="pass" class="ghost" '+(active?'':'disabled')+'>End turn</button>')+'</div>'+
 '<section class="log"><h3>Game log</h3>'+game.log.slice(0,14).map(x=>'<p>'+esc(x)+'</p>').join('')+'</section>'+
 '<p class="help"><b>LAB RULE:</b> A blocked Cause Trouble deals no Antics at all. The troublemaker and blocker fight with Power. This intentionally prevents Power from becoming the win-condition stat again.</p>';
 wireCards();
 root.querySelector('#pass')?.addEventListener('click',()=>humanAction(()=>game.pass()));
 root.querySelector('#new')?.addEventListener('click',()=>{game=null;phase='setup';render()});
 if(modal)showModal(modal);
}
function head(p,you){const s=game.players[p],d=game.decks[p],l=LEADERS[d.leader];return '<div class="head '+(you?'you':'')+'"><article class="leader-card '+esc(l.style.toLowerCase())+'"><div class="leader-line"><div><span class="leader-label">♛ '+(you?'YOUR':'AI')+' LEADER · '+esc(d.styles.join(' + '))+'</span><h2>'+esc(d.leader)+'</h2></div><b class="leader-health">☄ '+s.hp+' Composure</b></div><p class="leader-passive"><strong>PASSIVE</strong> '+esc(l.passive)+'</p><div class="metrics"><span>Stash '+s.fuel+'/'+s.stash.length+' ready</span><span>Deck '+s.deck.length+'</span><span>Hand '+(you?s.hand.length:'?')+'</span></div></article></div>'}
function section(p){const items=game.players[p].board.filter(x=>game.card(x).type==='Item');return '<div class="section"><div class="sectionhead">'+(p===human?'Your':'Opponent’s')+' board <span>'+game.chars(p).length+'/5 Characters</span></div><div class="lane">'+(game.chars(p).map(x=>cardHTML(x,'board',p)).join('')||'<span class="empty">No Characters</span>')+'</div>'+(items.length?'<div class="sectionhead">Items</div><div class="lane">'+items.map(x=>cardHTML(x,'board',p)).join('')+'</div>':'')+'</div>'}
function cardHTML(x,zone,p,index,chosen=false){const c=game.card(x),on=zone==='board',char=c.type==='Character',rot=on&&!x.ready;const stats=char?(on?game.power(x):c.power)+' ⚔ · '+(on?Math.max(0,game.guard(x)-x.damage):c.guard)+' ⛨ · '+c.antics+' ☄':c.type;return '<button class="card type-'+c.type.toLowerCase()+' '+c.style.toLowerCase()+' '+(rot?'rotated ':'')+(chosen?'mulligan-selected':'')+'" data-zone="'+zone+'" data-player="'+p+'" data-uid="'+(x.uid||'')+'" data-index="'+(index??'')+'"><span class="type-row"><span class="type-badge"><i>'+mark(c.type)+'</i> '+esc(c.type)+'</span><span>'+(on&&rot?'↷':'COST '+c.cost)+'</span></span><span class="style-name">'+esc(c.style)+'</span><b>'+esc(c.name)+'</b>'+(c.subtitle?'<span class="sub">'+esc(c.subtitle)+'</span>':'')+'<span class="summary">'+esc(c.text||c.flavor||'')+'</span><span class="numbers"><span>'+esc(stats)+'</span>'+(on&&char&&x.damage?'<span class="damage">♥ −'+x.damage+'</span>':'')+'</span></button>'}
function wireCards(){root.querySelectorAll('.card').forEach(b=>b.onclick=()=>{if(phase==='mulligan'){const i=+b.dataset.index;selected.has(i)?selected.delete(i):selected.add(i);render();return}if(b.dataset.zone==='hand')detail({id:game.players[human].hand[+b.dataset.index],handIndex:+b.dataset.index});else detail({uid:+b.dataset.uid})})}
function detail(ref){const x=ref.uid?game.obj(ref.uid):null,c=game.card(x||ref.id);if(!c)return;const me=game.turn===human&&!busy&&game.winner===null,own=x?.owner===human;const play=ref.handIndex!==undefined&&me&&game.canPlay(ref.handIndex,human),stash=ref.handIndex!==undefined&&me&&game.canStash(ref.handIndex,human),attack=x&&own&&c.type==='Character'&&me&&game.canAttack(x),trouble=x&&own&&c.type==='Character'&&me&&game.canCauseTrouble(x),act=x&&me&&game.canUse(x);let buttons='<button class="ghost" id="close">Close</button>'+(stash?'<button class="ghost" id="stash">Stash</button>':'')+(play?'<button class="primary" id="play">Play</button>':'')+(attack?'<button class="primary" id="attack">Attack Character</button>':'')+(trouble?'<button class="primary" id="trouble">Cause Trouble · '+c.antics+'</button>':'')+(act?'<button class="primary" id="activate">Activate</button>':'');let stats='<span>Cost '+c.cost+'</span>'+(c.type==='Character'?'<span>⚔ '+(x?game.power(x):c.power)+' Power</span><span>⛨ '+(x?game.guard(x):c.guard)+' Guard</span><span>☄ '+c.antics+' Antics</span>':'')+(x?'<span>'+(x.ready?'Ready':'Rotated')+'</span>':'');modal={kind:'detail',html:'<div class="overlay"><article class="sheet"><div class="type">'+esc(c.type)+' · '+esc(c.style)+' · '+esc(c.id)+'</div><h2>'+esc(c.name)+'</h2><div class="stats">'+stats+'</div><p class="rule">'+esc(c.text||c.flavor||'No special ability.')+'</p><div class="buttons">'+buttons+'</div></article></div>'};showModal(modal);document.querySelector('#close')?.addEventListener('click',close);document.querySelector('#stash')?.addEventListener('click',()=>{const i=ref.handIndex;close();humanAction(async()=>game.stash(i))});document.querySelector('#play')?.addEventListener('click',()=>{close();humanAction(()=>game.play(ref.handIndex))});document.querySelector('#attack')?.addEventListener('click',()=>{close();humanAction(()=>game.attack(x.uid))});document.querySelector('#trouble')?.addEventListener('click',()=>{close();humanAction(()=>game.causeTrouble(x.uid))});document.querySelector('#activate')?.addEventListener('click',()=>{close();humanAction(()=>game.activate(x.uid))})}
function showModal(entry){document.querySelector('.overlay')?.remove();if(!entry)return;document.body.insertAdjacentHTML('beforeend',entry.html);const overlay=document.querySelector('.overlay');overlay.onclick=e=>{if(e.target===overlay&&entry.kind==='detail')close()}}
function close(){modal=null;document.querySelector('.overlay')?.remove()}
async function ask(r){if(r.player!==human)return aiChoice(game,r);return new Promise(resolve=>{let chosen=[];const html='<div class="overlay"><div class="sheet"><div class="type">Choose</div><h2>'+esc(r.title)+'</h2>'+(r.attackContext?'<div class="attack-context"><strong>'+esc(r.attackContext.name)+' · '+esc(r.attackContext.power)+' Power</strong><span>Guard '+esc(r.attackContext.guard)+' · Damage '+esc(r.attackContext.damage)+'</span></div>':'')+'<p class="muted">'+(r.multi?'Choose up to '+(r.max||r.options.length)+'.':'Choose one.')+'</p>'+r.options.map((o,i)=>'<button class="choice" data-c="'+i+'">'+esc(o.label)+'</button>').join('')+'<div class="modal-actions">'+(r.mandatory?'':'<button id="cancel" class="ghost">Cancel</button>')+(r.multi?'<button id="done" class="primary">Confirm 0</button>':'')+'</div></div></div>';modal={kind:'choice',html};showModal(modal);const finish=v=>{close();resolve(v)};document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{const i=+b.dataset.c;if(!r.multi)return finish(r.options[i].value);if(chosen.includes(i)){chosen=chosen.filter(x=>x!==i);b.classList.remove('selected')}else if(!r.max||chosen.length<r.max){chosen.push(i);b.classList.add('selected')}document.querySelector('#done').textContent='Confirm '+chosen.length});document.querySelector('#cancel')?.addEventListener('click',()=>finish(r.multi?[]:null));document.querySelector('#done')?.addEventListener('click',()=>finish(chosen.map(i=>r.options[i].value)))})}
function start(a,b){human=0;game=new Game(pool,{...decks,decks:[decks.decks[a],decks.decks[b]]},ask,()=>{if(phase==='playing'&&!modal)render()},{firstPlayer:human});const ai=1-human;game.mulligan(ai,[]);phase='mulligan';render()}
async function humanAction(fn){if(busy||game.turn!==human)return;busy=true;render();try{await fn()}catch(e){console.error(e);alert(e.message)}finally{busy=false;render();await aiTurn()}}
async function aiTurn(){if(phase!=='playing'||!game||game.winner!==null||game.turn===human||busy)return;busy=true;render();let n=0;try{while(game.turn!==human&&game.winner===null&&n++<70){await new Promise(r=>setTimeout(r,170));const m=aiAction(game,game.turn);if(m.type==='pass')await game.pass();else if(m.type==='stash')game.stash(m.index,game.turn);else if(m.type==='attack')await game.attack(m.uid);else if(m.type==='trouble')await game.causeTrouble(m.uid);else if(m.type==='play')await game.play(m.index);else if(m.type==='activate')await game.activate(m.uid);render()}if(n>=70)throw Error('AI action limit reached')}finally{busy=false;render()}}
