import {Game} from './engine.mjs';
import {chooseMove} from './ai.mjs';
const root=document.querySelector('#app'),dialog=document.querySelector('#detail');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let pool,doc,g,mode='bot',view=0,curtain=false,busy=false,selected=new Set(),setupIndices=[0,6];
const rulesText=`<p><b>Win:</b> reduce the opposing Leader from 25 Health to 0. Each deck has 40 cards. First player skips their first draw; the second receives a one-use Stash.</p><p><b>Stash:</b> once per Turn, turn any hand card into a resource. Each Ready Stash pays 1. Your Stash Readies at the start of your Turn; Scientist has its own battery rule.</p><p><b>Characters:</b> enter Ready and can Block immediately. They normally wait until your next Turn to Attack or Work. Attacking and Blocking Rotate them. Damage stays.</p><p><b>Combat:</b> Attack the Leader or a Rotated enemy Character. One Ready Character can Block a Leader attack. Characters deal damage simultaneously, even if defeated. Damage beyond a Blocker’s remaining Guard reaches its Leader. Direct Character attacks cannot be Blocked.</p><p><b>Work:</b> once per Turn, spend 1 Stash and Rotate one eligible Character. It is exposed and cannot Block. If it survives in play until your next Turn, gain 1 Scheme progress. Three progress resolves your Leader’s Scheme once per game. Removing a worker cancels that job; earned progress stays.</p><p><b>Responses:</b> after targets and any Blocker are chosen, the defender may play one Response. If they pass, the attacker may play one. Then combat resolves. Responses cannot be answered.</p><p><b>Keywords:</b> Hothead can Attack immediately; Sucker Punch can Attack Ready Characters; Bodyguard is attackable while Ready and must Block a Leader attack if able; Stubborn stops the first Return or Dismiss each Round; Explosive deals 1 to every opposing Character when Defeated; Slowpoke does not deal combat damage while Blocking.</p><p><b>Testing:</b> this is the Scheme LAB, with its own 71-card pool and eight decks. It is not canonical Carl. In the comparison modes, the selected combat rule replaces simultaneous damage and Schemes are disabled.</p>`;
function modal(html){dialog.innerHTML=html;dialog.showModal();dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dialog.close());}
function rules(){modal(`<h2>How to play</h2><div class="rules">${rulesText}</div><button data-close class="btn-close">Close rules</button>`)}
async function boot(){try{[pool,doc]=await Promise.all(['CARDS.json','DECKS.json'].map(async file=>{const r=await fetch(file);if(!r.ok)throw Error('Could not load '+file);return r.json()}));renderSetup();}catch(e){root.innerHTML=`<div class="setup error"><h1>Couldn’t load the game</h1><p>${esc(e.message)}</p><button onclick="location.reload()">Try again</button></div>`;console.error(e);}}
function renderSetup(){
 const options=doc.decks.map((d,i)=>`<option value="${i}">${esc(d.leader)}</option>`).join('');
 root.innerHTML=`<div class="setup"><div class="eyebrow">Unhinged · Scheme Lab 0.1 · Testing</div><h1>Start trouble.<br>Finish your Scheme.</h1><p>Fight for space. Keep someone back. Or put a Character to work on the ridiculous plan that makes your Leader yours.</p><div class="setup-grid"><div class="field"><label for="deck-a">Your Leader / Player 1</label><select id="deck-a">${options}</select><div id="preview-a" class="preview"></div></div><div class="field"><label for="deck-b">Opponent / Player 2</label><select id="deck-b">${options}</select><div id="preview-b" class="preview"></div></div></div><div class="field"><label for="mode">Play mode</label><select id="mode"><option value="bot">Play against the bot</option><option value="local">Two players · pass the device</option></select></div><details><summary>Compare rules</summary><p class="muted">All comparisons use these same eight LAB decks.</p><label for="variant">Rules for this match</label><select id="variant"><option value="schemes">Full proposal · simultaneous damage + Schemes</option><option value="simultaneous">Simultaneous damage · no Schemes</option><option value="survivor">Surviving defenders retaliate · no Schemes</option><option value="none">No retaliation · no Schemes</option></select></details><button id="start" class="primary">Start match</button> <button id="rules">How to play</button><p class="footer-links"><a href="../../web/">Carl playtest</a> · <a href="../playtest/">Earlier LAB</a> · <a href="https://github.com/jobeck17/unhinged/tree/main/lab/schemes">Rules and design notes</a></p><p class="muted">Eight complete decks · 25 Health · 40 cards · one Scheme per Leader</p></div>`;
 const a=root.querySelector('#deck-a'),b=root.querySelector('#deck-b');a.value=setupIndices[0];b.value=setupIndices[1];
 function preview(el,i){const l=doc.leaders[i];root.querySelector(el).innerHTML=`<p><b>${esc(l.style)}</b></p><p>${esc(l.passive)}</p><p><b>SCHEME · ${esc(l.scheme)}</b><br>${esc(l.schemeText)}</p>`;}
 a.onchange=()=>preview('#preview-a',+a.value);b.onchange=()=>preview('#preview-b',+b.value);a.onchange();b.onchange();
 root.querySelector('#rules').onclick=rules;root.querySelector('#start').onclick=()=>{mode=root.querySelector('#mode').value;setupIndices=[+a.value,+b.value];const v=root.querySelector('#variant').value;g=new Game(pool,doc,setupIndices,{combat:v==='schemes'?'simultaneous':v,schemes:v==='schemes'});window.game=g;view=0;curtain=mode==='local';selected.clear();render();};
}
function cardHTML(x,p,zone,index){const c=g.card(x),board=zone==='board',char=c.type==='Character',worker=board&&g.players[p].worker===x.uid;return `<button class="game-card ${board&&!x.ready?'rotated':''} ${worker?'working':''} ${zone==='hand'&&g.phase==='mulligan'&&selected.has(index)?'selected':''}" data-zone="${zone}" data-player="${p}" data-index="${index??''}" data-uid="${x.uid||''}" aria-label="${esc(c.name)}, ${board?x.ready?'Ready':'Rotated':'Cost '+c.cost}${worker?', working on Scheme':''}"><span class="cost"><span>${esc(c.type)}</span><span>${board?(x.ready?'READY':'ROTATED'):'COST '+c.cost}</span></span><strong>${esc(c.name)}</strong><span class="text">${esc(c.text)}</span>${char?`<span class="stats"><span>⚔ ${board?g.power(x):c.power}</span><span>⛨ ${board?Math.max(0,g.remaining(x)):c.guard}${board&&x.damage?' left':''}</span></span>`:''}<span class="badge">${worker?'WORKING · SURVIVE TO SCORE':board&&char&&x.born>=g.players[p].turns?'NEW THIS TURN':esc(c.style)}</span><span class="detail-link">${g.phase==='mulligan'&&zone==='hand'?'Tap to keep / replace':'Tap for details & actions'}</span></button>`}
function leaderHTML(p){const s=g.players[p],l=g.leader(p);return `<div class="leader-head"><div><div class="leader-title"><h2>${esc(l.name)}</h2><b class="hp">♥ ${s.hp}</b></div><p class="passive">${esc(l.passive)}</p><div class="metrics"><span>Stash <b>${g.fuel(p)}/${s.stash.length}</b> Ready</span><span>Deck ${s.deck.length}</span><span>Hand ${s.hand.length}</span></div></div>${g.rules.schemes?`<div class="scheme-box"><h3>${esc(l.scheme)}</h3><div class="progress" aria-label="${s.progress} of 3 Scheme progress">${[1,2,3].map(i=>`<span class="step ${s.progress>=i?'done':''}"></span>`).join('')}</div><p>${esc(l.schemeText)}</p><span class="worker-note">${s.completed?'COMPLETED · once per game':s.worker?esc(g.card(g.obj(s.worker)).name)+' is working · opponent can disrupt':'Once per Turn: 1 Stash + Rotate a Character · survive to progress'}</span></div>`:''}</div>`}
function playerHTML(p){return `<section class="player-area" aria-label="${p===view?'Your':'Opponent’s'} play area">${leaderHTML(p)}<div class="area-label">${p===view?'Your':'Opponent’s'} board</div>${g.players[p].board.length?`<div class="cards">${g.players[p].board.map(x=>cardHTML(x,p,'board')).join('')}</div>`:'<p class="empty">No Characters or Items in play</p>'}</section>`}
function describe(m){const p=g.actor,s=g.players[p],name=uid=>uid===-1?'Leader':g.obj(uid)?g.card(g.obj(uid)).name:'none';switch(m.type){case'end':return'End Turn';case'block':return m.target?`Block with ${name(m.target)}`:'Take the attack';case'passResponse':return'Pass Response';case'respond':return`${g.card(s.hand[m.index]).name} → ${name(m.target)}`;case'discard':return`Discard ${g.card(s.hand[m.index]).name}`;case'choose':if(g.choice.kind==='rerollAbomination')return m.value==='keep'?'Keep '+g.power(g.obj(g.rerollTarget))+'/'+g.guard(g.obj(g.rerollTarget)):'Reroll '+m.value;return m.value===null?'Take no card':g.card(g.choice.kind==='findCard'?g.searchTop[m.value]:m.value).name;case'scheme':return m.targets?m.targets.length?'Return '+m.targets.map(name).join(' + '):'Return none':m.id?'Recover '+g.card(m.id).name:m.target?`${name(m.target)}: set ${m.stat} to 6`:'Resolve Scheme';case'play':return m.ingredients?'Fuse '+m.ingredients.map(i=>g.card(s.hand[i]).name).join(' + '):m.second?`Sacrifice ${name(m.target)} → damage ${name(m.second)}`:m.target?'Play → '+name(m.target):'Play'+(g.card(s.hand[m.index]).target?' without optional effect':'');case'attack':return`Attack ${name(m.target)}${m.risk?' · take 1 damage for boost':''}`;case'work':return'Work on Scheme · 1 Stash';case'activate':return'Heal '+name(m.target);case'stash':return'Stash this card';default:return m.type;}}
function render(){
 if(!g)return renderSetup();
 if(curtain){root.innerHTML=`<div class="curtain"><div class="eyebrow">Local two-player</div><h1>Pass to Player ${g.actor+1}.</h1><p>${esc(g.name(g.actor))} has a decision to make.<br>Hands stay hidden until you’re ready.</p><button id="reveal" class="primary">Player ${g.actor+1} is ready</button></div>`;root.querySelector('#reveal').onclick=()=>{view=g.actor;curtain=false;render()};return;}
 const canAct=!busy&&(mode==='local'||g.actor===0)&&g.winner===null;
 root.innerHTML=`<header class="topbar"><div><span class="brand">UNHINGED.</span><div class="mode-label">Scheme Lab · Round ${g.round} · ${g.rules.combat}${g.rules.schemes?' + Schemes':''}</div></div><button id="rules" class="ghost">Rules</button></header><div class="table">${g.winner!==null?`<div class="action-panel"><h1 class="winner">${esc(g.name(g.winner))} wins.</h1><p>${esc(g.endReason)} · ${g.round} Rounds</p><button id="new" class="primary">New matchup</button></div>`:''}${playerHTML(1-view)}${playerHTML(view)}<section class="player-area hand-area"><div class="area-label">${g.phase==='mulligan'?'Select cards to replace':'Your hand'} · ${esc(g.name(view))}</div><div class="cards">${g.players[view].hand.map((id,i)=>cardHTML({id},view,'hand',i)).join('')||'<p class="empty">No cards in hand</p>'}</div><div class="turn-controls"><p>${busy?'Bot is thinking…':g.winner!==null?'Match complete':esc(g.name(g.actor))+' · '+(g.phase==='main'?'play, Attack, protect, or Work':g.phase)}</p>${g.phase==='main'&&canAct?'<button id="end" class="primary">End Turn</button>':''}${g.phase==='mulligan'&&canAct?`<button id="mulligan" class="primary">${selected.size?'Replace '+selected.size:'Keep hand'}</button>`:''}</div></section></div><div id="decision"></div><details class="game-log" open><summary>Game log</summary>${g.log.slice(0,12).map(s=>`<p>${esc(s)}</p>`).join('')}</details>`;
 root.querySelector('#rules').onclick=rules;root.querySelector('#new')?.addEventListener('click',()=>{g=null;window.game=null;renderSetup()});root.querySelector('#end')?.addEventListener('click',()=>act({type:'end'}));root.querySelector('#mulligan')?.addEventListener('click',()=>act({type:'mulligan',indices:[...selected]}));
 root.querySelectorAll('[data-zone]').forEach(b=>b.onclick=()=>{const hand=b.dataset.zone==='hand',index=+b.dataset.index;if(g.phase==='mulligan'&&hand&&canAct){selected.has(index)?selected.delete(index):selected.add(index);render();}else showCard(hand?{index}:{uid:+b.dataset.uid});});
 if(canAct&&!['main','mulligan'].includes(g.phase)){
  const moves=g.legalMoves(),title={block:'Choose a Blocker',response:'Response opportunity',discard:'Choose a card to discard',choose:'Choose a card',scheme:'Finish your Scheme'}[g.phase];
  const combat=g.pending?`<p>${esc(g.card(g.obj(g.pending.attacker)).name)} attacks ${g.pending.target===-1?esc(g.name(1-g.turn)):esc(g.card(g.obj(g.pending.target)).name)}.${g.pending.defender?' Combat defender: '+esc(g.card(g.obj(g.pending.defender)).name)+'.':''}</p>`:'';
  root.querySelector('#decision').innerHTML=`<section class="action-panel"><h2>${title}</h2>${combat}<div class="choices">${moves.map((m,i)=>`<button data-move="${i}">${esc(describe(m))}</button>`).join('')}</div></section>`;
  root.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>act(moves[+b.dataset.move]));
 }
}
function showCard(ref){
 const x=ref.uid?g.obj(ref.uid):null,c=g.card(x||g.players[view].hand[ref.index]);if(!c)return;
 const canAct=!busy&&g.actor===view&&g.winner===null;
 const moves=canAct?g.legalMoves().filter(m=>ref.uid?m.uid===ref.uid:['play','stash'].includes(m.type)&&m.index===ref.index):[];
 const groups=[...new Set(moves.map(m=>m.type))];
 modal(`<div class="eyebrow" style="color:#58696b">${esc(c.type)} · ${esc(c.style)} · Cost ${c.cost}</div><h2>${esc(c.name)}</h2><p>${esc(c.text||'No special ability.')}</p>${c.type==='Character'?`<p><b>${x?g.power(x):c.power} Power / ${x?g.guard(x):c.guard} Guard</b>${x?' · '+x.damage+' damage · '+(x.ready?'Ready':'Rotated'):''}</p>`:''}<p class="hint">${esc(c.traits.join(' · '))}</p>${g.rules.schemes&&x&&c.type==='Character'?'<p class="small">Work costs 1 Ready Stash and Rotates this Character. It must have begun your Turn in play. Keep it alive until your next Turn to earn progress.</p>':''}<div class="modal-buttons">${groups.map(t=>`<button data-action="${t}" class="${t==='work'?'primary':''}">${{play:'Play',stash:'Stash',attack:'Attack',work:'Work · 1 Stash',activate:'Use Item'}[t]}</button>`).join('')}<button data-close>Close</button></div>`);
 dialog.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const opts=moves.filter(m=>m.type===b.dataset.action);if(opts.length===1){dialog.close();act(opts[0]);}else chooseOptions(opts,c.name);});
}
function chooseOptions(moves,title){dialog.innerHTML=`<h2>${esc(title)}</h2><p>Choose how to resolve this play.</p><div class="choice-list">${moves.map((m,i)=>`<button data-pick="${i}">${esc(describe(m))}</button>`).join('')}</div><button class="btn-close" data-close>Cancel</button>`;dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{dialog.close();act(moves[+b.dataset.pick]);});}
async function act(m){
 if(busy)return;
 try{g.apply(m);selected.clear();if(mode==='local'){if(g.actor!==view&&g.winner===null)curtain=true;render();return;}render();busy=true;while(g.winner===null&&g.actor===1){render();await new Promise(r=>setTimeout(r,120));g.apply(chooseMove(g));}busy=false;render();}
 catch(e){busy=false;console.error(e);modal(`<h2>That move could not finish</h2><p>${esc(e.message)}</p><button data-close>Close</button>`);render();}
}
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&dialog.open)dialog.close()});
boot();
