import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Game} from './engine.mjs';
import {chooseMove} from './ai.mjs';
const pool=JSON.parse(fs.readFileSync(new URL('./CARDS.json',import.meta.url)));
const doc=JSON.parse(fs.readFileSync(new URL('./DECKS.json',import.meta.url)));
const id=x=>'LAB-SCH-'+x;
let count=0;
function test(name,fn){fn();count++;console.log('PASS '+name)}
function setup(a=1,b=2,opts={}){const g=new Game(pool,doc,[a,b],{seed:123,firstPlayer:0,...opts});g.apply({type:'mulligan',indices:[]});g.apply({type:'mulligan',indices:[]});g.round=3;g.serial=5;for(const s of g.players){s.turns=3;s.hand=[];s.board=[];s.stash=Array.from({length:6},()=>({id:id('U1'),ready:true,temp:false}));s.discard=[];}g.turn=0;g.actor=0;g.phase='main';return g}
function creature(g,p,key,extra={}){return g.enter(p,id(key),{born:2,...extra})}
function applyType(g,type,predicate=()=>true){const m=g.legalMoves().find(m=>m.type===type&&predicate(m));assert(m,`Missing ${type}`);g.apply(m)}
function passCombat(g){let n=0;while(g.pending&&n++<5){if(g.phase==='block')applyType(g,'block');else applyType(g,'passResponse');}assert(n<=5)}
test('40-card decks, known IDs, legal copy counts and unique cards',()=>{assert.equal(new Set(pool.cards.map(c=>c.id)).size,pool.cards.length);for(const d of doc.decks){assert.equal(Object.values(d.cards).reduce((a,b)=>a+b,0),40);for(const [cid,n]of Object.entries(d.cards)){assert(pool.cards.some(c=>c.id===cid));assert(n<=4||(cid===id('C1')&&n<=10));}}});
test('deterministic seed preserves opening hands',()=>{assert.deepEqual(new Game(pool,doc,[0,1],{seed:10}).players,new Game(pool,doc,[0,1],{seed:10}).players)});
test('mulligan has no duplicates or out of range selections',()=>{const g=new Game(pool,doc);assert.throws(()=>g.apply({type:'mulligan',indices:[0,0]}));assert.throws(()=>g.apply({type:'mulligan',indices:[10]}));});
test('second player setup Stash readies and is consumed once',()=>{const g=new Game(pool,doc,[0,1],{seed:4,firstPlayer:0});g.apply({type:'mulligan',indices:[]});g.apply({type:'mulligan',indices:[]});assert.equal(g.players[0].hand.length,7);assert.equal(g.fuel(1),0);g.apply({type:'end'});assert.equal(g.fuel(1),1);assert.equal(g.players[1].hand.length,8);g.pay(1,1);assert.equal(g.players[1].stash.length,0);});
test('illegal actions preserve state',()=>{const g=setup(),before=JSON.stringify(g.players);assert.throws(()=>g.apply({type:'work',uid:999}));assert.equal(JSON.stringify(g.players),before)});
test('new Hothead may attack but cannot work',()=>{const g=setup(),x=g.enter(0,id('R5'));assert(g.canAttack(x));assert(!g.canWork(x))});
test('work costs readiness and Stash; only once per Turn',()=>{const g=setup(),x=creature(g,0,'H2'),y=creature(g,0,'R1');const fuel=g.fuel(0);g.apply({type:'work',uid:x.uid});assert.equal(g.fuel(0),fuel-1);assert(!x.ready);assert(!g.canAttack(x));assert(!g.canWork(y));assert.equal(g.players[0].progress,0);});
test('work scores only after opponent Turn and preserves earlier progress on interruption',()=>{const g=setup(),x=creature(g,0,'H2');g.players[0].progress=1;g.apply({type:'work',uid:x.uid});g.apply({type:'end'});assert.equal(g.players[0].progress,1);g.returnCard(x);assert.equal(g.metrics[0].interrupted,1);g.apply({type:'end'});assert.equal(g.players[0].progress,1);});
test('third survived job completes once per game',()=>{const g=setup(4,2),x=creature(g,0,'H2');g.players[0].progress=2;g.apply({type:'work',uid:x.uid});g.apply({type:'end'});g.apply({type:'end'});assert.equal(g.phase,'scheme');assert.equal(g.players[0].progress,3);const hp=g.players[1].hp;applyType(g,'scheme');assert.equal(g.players[1].hp,hp-8);assert(!g.canWork(x));});
test('simultaneous lethal damage removes both combatants',()=>{const g=setup(),a=creature(g,0,'R2',{damage:1}),d=creature(g,1,'R2',{damage:1,ready:false});applyType(g,'attack',m=>m.uid===a.uid&&m.target===d.uid);passCombat(g);assert(!g.obj(a.uid));assert(!g.obj(d.uid));});
test('survivor and no-retaliation switches are isolated controls',()=>{for(const combat of ['survivor','none']){const g=setup(1,2,{combat}),a=creature(g,0,'R2',{damage:1}),d=creature(g,1,'R2',{damage:1,ready:false});applyType(g,'attack',m=>m.target===d.uid);passCombat(g);assert(g.obj(a.uid));assert(!g.obj(d.uid));}});
test('Bodyguard forces a block; newly played Characters can block',()=>{const g=setup(),a=creature(g,0,'R2'),d=g.enter(1,id('H3'));applyType(g,'attack',m=>m.target===-1);assert.equal(g.phase,'block');assert(g.legalMoves().every(m=>m.target===d.uid));});
test('overflow hits Leader while both Characters deal damage',()=>{const g=setup(),a=creature(g,0,'C7'),d=creature(g,1,'R2');applyType(g,'attack',m=>m.target===-1);applyType(g,'block',m=>m.target===d.uid);passCombat(g);assert.equal(g.players[1].hp,22);assert.equal(a.damage,2);assert(!g.obj(d.uid));});
test('Slowpoke does not deal damage while blocking',()=>{const g=setup(),a=creature(g,0,'R2'),d=creature(g,1,'S6');applyType(g,'attack',m=>m.target===-1);applyType(g,'block',m=>m.target===d.uid);passCombat(g);assert.equal(a.damage,0)});
test('Slowpoke still deals damage as a direct attack target',()=>{const g=setup(),a=creature(g,0,'R2'),d=creature(g,1,'S6',{ready:false});applyType(g,'attack',m=>m.target===d.uid);passCombat(g);assert(!g.obj(a.uid));assert(!g.obj(d.uid));});
test('defender has first Response; one Response closes window',()=>{const g=setup(),a=creature(g,0,'R2'),d=creature(g,1,'R2',{ready:false});g.players[1].hand=[id('U3')];g.players[0].hand=[id('U4')];applyType(g,'attack',m=>m.target===d.uid);assert.equal(g.actor,1);applyType(g,'respond');assert.equal(g.phase,'main');assert.equal(g.actor,0);assert.equal(d.damage,0);assert.equal(a.damage,2);assert.equal(g.players[0].hand.length,1);});
test('Cheap Shot can kill attacker and cancel combat',()=>{const g=setup(),a=creature(g,0,'R3'),d=creature(g,1,'R2',{ready:false});g.players[1].hand=[id('U4')];applyType(g,'attack',m=>m.target===d.uid);applyType(g,'respond',m=>m.target===a.uid);assert(!g.obj(a.uid));assert.equal(d.damage,0);});
test('Stubborn stops Return once per Round but never lethal damage',()=>{const g=setup(),x=creature(g,0,'C5');g.returnCard(x);assert(g.obj(x.uid));g.returnCard(x);assert(!g.obj(x.uid));const y=creature(g,0,'C5');g.damageMany([[y,4]]);assert(!g.obj(y.uid));});
test('a wipe defeats all initial casualties before Explosive triggers',()=>{const g=setup(),a=creature(g,0,'W5'),d=creature(g,1,'R2'),survivor=creature(g,1,'H2');g.damageMany([[a,3],[d,3],[survivor,3]]);assert(!g.obj(a.uid));assert(!g.obj(d.uid));assert(!g.obj(survivor.uid));assert.equal(g.metrics[1].deaths,2);});
test('Cat economy is conditional discount and creates no permanent Stash',()=>{const g=setup(6,2);for(let i=0;i<3;i++)creature(g,0,'C1');const before=g.players[0].stash.length;assert.equal(g.cost(0,g.card(id('C2'))),1);g.defeatBatch([g.chars(0)[0]]);assert.equal(g.cost(0,g.card(id('C2'))),2);assert.equal(g.players[0].stash.length,before)});
test('Trash Baron cannot spend opposing Stash',()=>{const g=setup(3,2);g.players[0].stash=[];g.players[0].hand=[id('R1')];assert(!g.legalMoves().some(m=>m.type==='play'));});
test('Scientist setup and recharge; no normal Stash action',()=>{const g=new Game(pool,doc,[7,2],{seed:4,firstPlayer:0});g.apply({type:'mulligan',indices:[]});g.apply({type:'mulligan',indices:[]});assert.equal(g.fuel(0),5);assert(!g.legalMoves().some(m=>m.type==='stash'));g.pay(0,5);g.apply({type:'end'});g.apply({type:'end'});assert.equal(g.fuel(0),3);});
test('fusion consumes exactly two ingredients and independent fixed-order rolls',()=>{const g=setup(7,2);g.players[0].hand=[id('S8'),id('S1'),id('S3')];const values=[0,.99];g.random=()=>values.shift();applyType(g,'play');assert.equal(g.players[0].hand.length,0);const x=g.chars(0)[0];assert.equal(g.power(x),1);assert.equal(g.guard(x),6);assert.equal(g.players[0].discard.length,3);});
test('putting a Character in play does not trigger On Play',()=>{const g=setup(5,2);g.players[0].discard=[id('R4')];g.phase='scheme';const n=g.players[0].hand.length;applyType(g,'scheme',m=>m.id===id('R4'));assert.equal(g.players[0].hand.length,n);assert.equal(g.phase,'main');assert(g.chars(0)[0].hot);});
test('simultaneous game-ending effects finish before winner selection',()=>{const g=setup();g.players[0].hp=1;g.players[1].hp=1;const x=creature(g,0,'W2'),y=creature(g,1,'W2');g.resolving=true;g.damageMany([[x,2],[y,2]]);assert.equal(g.winner,null);g.resolving=false;g.checkEnd();assert.equal(g.endReason,'War');});
test('all eight decks finish deterministic smoke games without illegal AI moves',()=>{for(let i=0;i<8;i++){const g=new Game(pool,doc,[i,(i+1)%8],{seed:500+i,firstPlayer:i%2});let n=0;while(g.winner===null&&g.round<30&&n++<2000)g.apply(chooseMove(g));assert(g.winner!==null,`${i} did not finish`);assert(n<2000);}});
test('fusion permits one reroll and cannot choose die assignment afterward',()=>{const g=setup(7,2);g.players[0].hand=[id('S8'),id('S1'),id('S2')];const dice=[0,.99,.8];g.random=()=>dice.shift();applyType(g,'play');assert.equal(g.phase,'choose');applyType(g,'choose',m=>m.value==='Power');const x=g.chars(0)[0];assert.equal(g.power(x),5);assert.equal(g.guard(x),6);assert.equal(g.phase,'main');assert(!g.legalMoves().some(m=>m.type==='choose'));});
test('Cat recovery uses discard cards and does not grant immediate Work',()=>{const g=setup(6,2);g.players[0].hand=[id('C7')];g.players[0].discard=[id('C1'),id('C1')];applyType(g,'play');assert.equal(g.chars(0).length,3);assert.equal(g.players[0].discard.length,0);assert(g.chars(0).every(x=>!g.canWork(x)));});
test('Rock Star low-hand gate does not reward a full hand',()=>{const g=setup(1,2);g.players[0].played=1;g.players[0].hand=Array(5).fill(id('R1'));applyType(g,'play');assert.equal(g.players[0].hand.length,4);g.players[0].played=1;g.players[0].hand=Array(3).fill(id('R1'));applyType(g,'play');assert.equal(g.players[0].hand.length,3);});
test('Return during combat cancels the pending job even if replayed later',()=>{const g=setup(2,1),x=creature(g,0,'M1');g.players[0].progress=1;g.apply({type:'work',uid:x.uid});g.returnCard(x);const y=g.enter(0,id('M1'));assert.notEqual(y.uid,x.uid);assert.equal(g.players[0].worker,null);assert.equal(g.players[0].progress,1);});
test('drawing from empty during a multi-step effect checks after its final choice',()=>{const g=setup();g.players[0].deck=[];g.players[0].hand=[id('R8'),id('R1')];applyType(g,'play',m=>m.index===0);assert.equal(g.phase,'discard');assert.equal(g.winner,null);applyType(g,'discard');assert.equal(g.winner,1);});
console.log(`Final: ${count} tests passed`);
