// This is a vocabulary survey, not a rule change. Examples follow RULES.md.
export const VERSION = 'mordecai-vocabulary-2026-10-06-v1';
export const sections = [
  {title:'The big labels',short:'01 · Foundations',intro:'Start with the resource pool and the word for the six card families.'},
  {title:'Six identities. Six names.',short:'02 · Styles',intro:'These identity summaries come from the current baseline decks. Vote on the names, not a change to how the decks work. Alternatives are suggestions.'},
  {title:'Words at the table',short:'03 · Table talk',intro:'Choose the words that feel clear when someone explains a turn out loud.'},
  {title:'Leaders & the final straw',short:'04 · Endgame',intro:'The current Leader track is 20 Composure, Breaking Point at 10, Last Straw at 0, then a later successful Cause Trouble makes the Leader Unhinged.'}
];
export const questions = [
 {id:'resource',section:0,title:'Should the resource pool be called “Stash”?',current:'Stash',context:'Once per Round on your Turn, you may put a card from hand face-down into this row. Each Ready card pays 1 toward a Cost when Rotated. All Styles use the same resource system.',examples:['“Put a card from your hand into your Stash.”','“Rotate 3 Stash to play this Character.”'],choices:['Stash','Resources','Supply','Fuel']},
 {id:'family',section:0,title:'Should the six card pools be called “Styles”?',current:'Styles',context:'Reckless, Momentum, Misdirection, Salvage, Stonewall, and Expendable are card families with different play identities. A standard deck can use its Leader’s family plus up to one additional family. These are card pools, separate from the Stash resource pool.',examples:['“Florida Man’s Style is Reckless.”','“Choose up to one secondary Style for your deck.”'],choices:['Styles','Approaches','Attitudes','Factions']},
 {id:'reckless',section:1,title:'Does “Reckless” fit this identity?',current:'Reckless',accent:'#ef8672',leader:'Florida Man · Bad Decisions',identity:'Take risks. Turn self-damage and damaged Characters into advantages; spread damage and push through consequences.',examples:['“I’m playing a Reckless deck.”','“That Character rewards me for taking a risk.”'],choices:['Reckless','Unruly','Wild','Chaotic']},
 {id:'momentum',section:1,title:'Does “Momentum” fit this identity?',current:'Momentum',accent:'#f0bf68',leader:'Washed-Up Rock Star · Comeback Tour',identity:'Keep the chain going. Play in sequences, use a low or empty hand as an advantage, then refill to sustain the next burst.',examples:['“My Leader is Momentum, with Salvage as my secondary Style.”','“Empty the hand, refill, keep the turn rolling.”'],choices:['Momentum','Hustle','Relentless','Encore']},
 {id:'misdirection',section:1,title:'Does “Misdirection” fit this identity?',current:'Misdirection',accent:'#be9bea',leader:'Birthday Party Magician · Now You See Me',identity:'Make things disappear and reappear. Return and replay Characters, reuse enter-play effects, and manipulate the board through deception and timing.',examples:['“This card belongs to Misdirection.”','“Return my Character, then replay it for another entrance.”'],choices:['Misdirection','Trickery','Cunning','Deception']},
 {id:'salvage',section:1,title:'Does “Salvage” fit this identity?',current:'Salvage',accent:'#80c7b1',leader:'Trash Baron · Curbside Empire',identity:'Make junk useful. Scrounge for cards, repurpose Items, Jerry-Rig discarded Items into temporary resources, and build value from what others throw away.',examples:['“I’m adding Salvage to my deck.”','“That broken Item still has one more use.”'],choices:['Salvage','Makeshift','Resourceful','Scrounge']},
 {id:'stonewall',section:1,title:'Does “Stonewall” fit this identity?',current:'Stonewall',accent:'#93bce9',leader:'HOA President · Violation Notice',identity:'Control the pace. Freeze, stall, and deny the opponent’s plans; turn restrictions and carefully timed interference into an advantage.',examples:['“Stonewall makes you work around its restrictions.”','“Slow their turn and buy time for my own plan.”'],choices:['Stonewall','Stubborn','Obstruction','Control']},
 {id:'expendable',section:1,title:'Does “Expendable” fit this identity?',current:'Expendable',accent:'#df98b6',leader:'Backyard Wrestler · Tag Team Trashfire',identity:'Make losses pay. Sacrifice Characters, gain value when they are Defeated, bring them back, and replace fallen bodies to keep the engine moving.',examples:['“Expendable gets value when its Characters are Defeated.”','“Lose a wrestler, tag in the next one.”'],choices:['Expendable','Disposable','Undying','Sacrificial']},
 {id:'rotate',section:2,title:'What should turning a card sideways be called?',current:'Rotate',context:'A Ready card is upright. Turning it sideways commits it to an Attack, Cause Trouble, a resource payment, or a Rotate ability. It becomes available again when Readied.',examples:['“Rotate this Character to Cause Trouble.”','“Ready your Rotated cards at the start of your Turn.”'],choices:['Rotate / Rotated','Exhaust / Exhausted','Commit / Committed','Use / Used']},
 {id:'cause-trouble',section:2,title:'Should the Leader-pressure action be “Cause Trouble”?',current:'Cause Trouble',context:'An eligible Ready Character with at least 1 Trouble Rotates to make the opposing Leader lose that much Composure. This is not combat and cannot be Blocked. The Character is then exposed to ordinary Attacks.',examples:['“This Character Causes Trouble for 2.”','“Attack a Character, Cause Trouble, or stay Ready?”'],choices:['Cause Trouble','Stir the Pot','Raise Hell','Rattle']},
 {id:'trouble',section:2,title:'Should the Leader-pressure stat be called “Trouble”?',current:'Trouble',context:'Characters have Attack, Health, and Trouble. Attack is for Character combat; Trouble measures how much Composure an opposing Leader loses when that Character Causes Trouble.',examples:['“This Character has 3 Attack, 2 Health, and 1 Trouble.”','“Give this Character +1 Trouble this Turn.”'],choices:['Trouble','Nuisance','Chaos','Pressure']},
 {id:'defeat',section:2,title:'Should removing a beaten Character be called “Defeat”?',current:'Defeat',context:'A Character is Defeated when accumulated damage reaches its Health. It goes from play to its owner’s discard. This is different from Dismiss, which removes a card without Defeating it.',examples:['“When this Character is Defeated, Draw a card.”','“Deal 3 damage and Defeat that Character.”'],choices:['Defeat / Defeated','Knock Out / Knocked Out','Wreck / Wrecked','Eliminate / Eliminated']},
 {id:'sacrifice',section:2,title:'What should giving up your own Character be called?',current:'Sacrifice',context:'The current term is Sacrifice: Defeat one of your own Characters as a cost or effect. It also counts as a Defeat. This wording is still subject to the card terminology audit.',examples:['“Sacrifice a Character: Draw 2 cards.”','“When you Sacrifice a Character, gain this bonus.”'],choices:['Sacrifice','Cash In','Throw Under the Bus','Ditch']},
 {id:'leader',section:3,title:'Should the deck’s central personality be called a “Leader”?',current:'Leader',context:'This visible card sits outside your deck, defines its identity, and provides a passive and unique Breaking Point. Leaders do not Attack or have Character Health.',examples:['“Choose your Leader before building your deck.”','“Florida Man is my Leader.”'],choices:['Leader','Ringleader','Instigator','Boss']},
 {id:'composure',section:3,title:'Should the Leader’s survival track be “Composure”?',current:'Composure',context:'Leaders begin at 20. Trouble wears this down. The name should describe someone getting pushed toward losing it, while staying distinct from Character Health.',examples:['“Your Leader loses 2 Composure.”','“Recover 3 Composure, up to 20.”'],choices:['Composure','Patience','Sanity','Cool']},
 {id:'breaking-point',section:3,title:'Should the halfway threshold be “Breaking Point”?',current:'Breaking Point',context:'The first time a Leader moves from above 10 Composure to 10 or less, its unique printed ability triggers. It triggers once per game.',examples:['“My Leader just hit Breaking Point.”','“Resolve your Leader’s Breaking Point ability.”'],choices:['Breaking Point','Short Fuse','On the Edge','Fed Up']},
 {id:'last-straw',section:3,title:'Should the hidden comeback card be “Last Straw”?',current:'Last Straw',context:'Choose one outside-deck card from a shared pool and hide it under your Leader. Normally it reveals at 0 Composure and gives one final comeback before a later successful opposing Cause Trouble makes your Leader Unhinged.',examples:['“Reveal and resolve your Last Straw.”','“I’m at Last Straw. One more successful Cause Trouble and I lose.”'],choices:['Last Straw','Final Nerve','Snap','Last Chance']},
 {id:'character',section:3,title:'Should the people and creatures you play be “Characters”?',current:'Characters',context:'These are the main cards on the battlefield: people, animals, weirdos, and other troublemakers with Attack, Health, and Trouble.',examples:['“Play a Character from your hand.”','“Choose a Ready Character you control.”'],choices:['Characters','Troublemakers','Units','Misfits']}
];
