import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Game,LEADERS} from './engine.js?v=mordecai-04-stonewall-01';
import './magician.js';import './cat-lady.js';import './rockstar.js';import './reckless.js';import './stonewall.js';
import {aiAction,aiChoice} from './ai.js';
const pool=JSON.parse(fs.readFileSync(new URL('../CARDS.json',import.meta.url))),doc=JSON.parse(fs.readFileSync(new URL('../DECKS.json',import.meta.url)));
const hoa=doc.decks.find(d=>d.leader==='HOA President'),fl=doc.decks[0],covered=new Set();let checks=0;
function ok(value,msg){assert(value,msg);checks++}
function eq(a,b,msg){assert.deepEqual(a,b,msg);checks++}
function fixture(decide){let g;g=new Game(pool,{decks:[hoa,fl]},async r=>{const v=decide?.(r,g);return v!==undefined?v:r.multi?[]:r.options[0]?.value??null},()=>{},{firstPlayer:0});g.round=3;g.turn=0;for(const s of g.players){s.board=[];s.hand=[];s.discard=[];s.deck=Array(80).fill('P001');s.stash=Array(20).fill('P001');s.fuel=20}satisfyDice(g,6);return g}
function satisfyDice(g,r){g.random=()=> (r-.5)/6}
function body(g,id,p=0,ready=true){if(g.card(id).style==='Stonewall')covered.add(id);const x=g.enter(p,id);x.born=0;x.ready=ready;return x}
async function play(g,id){covered.add(id);g.players[g.turn].hand.push(id);const i=g.players[g.turn].hand.length-1;ok(g.canPlay(i),'legal '+id);const before=g.players[g.turn].fuel,cost=g.playCost(g.turn,id);await g.play(i);eq(g.players[0].fuel,before-cost,'paid cost '+id)}
async function step(g,p){g.turn=p;g.startTurn();await g.flushEffects()}
eq(hoa.audit_card_ids.length,33,'preserve every lock, corrected count');eq(Object.values(hoa.cards).reduce((a,b)=>a+b),40,'40-card coverage deck');ok(hoa.audit_card_ids.every(id=>hoa.cards[id]),'all cards in deck');ok(!hoa.cards.P150,'Newsletter banked');
for(const id of ['LAB-HOA-001','P124','P128','P129','P133','P135','P137','P138','P130','LAB-HOA-003','P072','P125','P131','P132']){const g=fixture();await play(g,id);eq(g.players[0].board.length,1,'body '+id);eq(g.players[0].hand.length,0,'no legacy enter '+id)}
// Absorb is highest value, applies to effects and combat, never reduces existing damage.
{const g=fixture(),x=body(g,'P121');await g.damage(x,2);eq(x.damage,1,'Old Guy Absorb');const mom=body(g,'P072');body(g,'P072');g.players[0].digIn=true;eq(g.absorb(x),1,'auras do not stack');await g.damage(x,1);eq(x.damage,1,'zero damage ignored');eq(g.absorb(mom),1,'other Mom may protect first Mom')}
// Meat Shield only restricts attacks against legally attackable Rotated shields.
{const g=fixture(),a=body(g,'P012',1),target=body(g,'P124',0,false),shield=body(g,'P126',0,true);eq(g.attackTargets(a).map(x=>x.uid),[target.uid],'Ready shield inactive');shield.ready=false;eq(g.attackTargets(a).map(x=>x.uid),[shield.uid],'shield first');const second=body(g,'P129',0,false);eq(g.attackTargets(a).length,2,'choose shields');shield.cloaked=true;eq(g.attackTargets(a).map(x=>x.uid),[second.uid],'cannot attack cloak');second.ready=true;eq(g.attackTargets(a).map(x=>x.uid),[target.uid],'Ready shields do not protect even vs Sucker Punch');a.sucker=true;ok(g.attackTargets(a).some(x=>x.uid===second.uid),'Sucker hits Ready shield without redirect')}
for(const rotate of [true,false]){const g=fixture(r=>r.title.startsWith('Crossing Guard:')?rotate:undefined);await play(g,'P126');eq(g.chars(0)[0].ready,!rotate,'optional rotated entry')}
// Retaliate still deals captured Power after the defender is Defeated.
for(const id of ['P138','P128','P129','P133']){const g=fixture(),a=body(g,'P014',1),d=body(g,id,0,false);g.turn=1;a.power=10;g.ask=async r=>r.title.startsWith('Wannabe')?false:r.options[0]?.value;await g.attack(a.uid);ok(!g.obj(d.uid),'defender dies '+id);ok(!g.obj(a.uid)||a.damage===g.card(id).power,'retaliates on Defeat '+id)}
// No old Mall Cop shutdown; only Hothead Power penalty while Ready.
{const g=fixture(),cop=body(g,'P135'),hot=body(g,'P012',1),plain=body(g,'P001',1);eq(g.power(hot),3,'cop penalty');eq(g.power(plain),2,'nonHothead unchanged');cop.ready=false;eq(g.power(hot),4,'cop penalty switches off');cop.ready=true;g.turn=1;cop.ready=false;ok(g.canAttack(hot),'Hothead can attack');g.turn=0;cop.born=0;cop.ready=true;body(g,'P001',1,false);ok(g.canAttack(cop),'Mall Cop can attack')}
// On-play draw / heal, targeted rotation, capped item removal.
{const g=fixture();await play(g,'P134');eq(g.players[0].hand.length,1,'Usher Draw')}
for(const damaged of [true,false]){const g=fixture(),x=body(g,'P124');x.damage=damaged?3:0;await play(g,'P127');eq(x.damage,damaged?1:0,'PTA heal');eq(g.players[0].hand.length,damaged?1:0,'draw actual healing only')}
{const g=fixture(),small=body(g,'P001',1),large=body(g,'P133',1);await play(g,'LAB-HOA-002');ok(!small.ready&&large.ready,'Bicycle caps targets');eq(g.card(small).cost,1,'small cost')}
{const g=fixture(),x=body(g,'P133',1);await play(g,'P122');ok(!x.ready&&x.skipReady,'Committee rotate-delay');await step(g,1);ok(!x.ready&&!x.skipReady,'one skipped Ready');await step(g,1);ok(x.ready,'Readies following step')}
{const g=fixture(),item=g.enter(1,'P028'),big=g.enter(1,'P030');g.cards.P030={...g.cards.P030,cost:4};await play(g,'P136');ok(!g.obj(item.uid)&&g.obj(big.uid),'Tow caps 3');ok(g.players[1].discard.includes('P028'),'Item dismissed')}
// Actual transition triggers: Ready step, effect Ready, no entering/already Ready trigger.
{const g=fixture(),x=body(g,'P124'),old=body(g,'P131',0,false),grandma=body(g,'P132',0,false);x.damage=3;old.damage=2;await step(g,0);eq(old.damage,1,'Old Dog Ready-step heal');eq(x.damage,1,'Grandma Ready-step heal');await g.readyCharacter(grandma);eq(x.damage,1,'already Ready no trigger');grandma.ready=false;await g.readyCharacter(grandma);eq(x.damage,0,'effect Ready heals');old.ready=false;await g.readyCharacter(old);eq(old.damage,1,'Old Dog only step heal')}
// Lawn Chair: legal target, spend fuel, Rotate item, trigger Grandma, prohibit reuse.
{const g=fixture(),x=body(g,'P124'),grandma=body(g,'P132',0,false);x.damage=3;await play(g,'P148');const item=g.players[0].board.find(x=>x.id==='P148'),fuel=g.players[0].fuel;ok(g.canUse(item),'Lawn usable');await g.activate(item.uid);eq(g.players[0].fuel,fuel-1,'activation cost');eq(x.damage,1,'Chair triggers Grandma');ok(grandma.ready&&!item.ready,'ready and rotate');ok(!g.canAttack(grandma)&&!g.canCauseTrouble(grandma),'no double use');ok(!g.canUse(item),'once until Ready')}
{const g=fixture(),x=body(g,'P124',0,false);await play(g,'LAB-HOA-004');ok(x.ready&&!g.canAttack(x)&&!g.canCauseTrouble(x),'Breather restrictions');await g.pass();await step(g,0);ok(g.canCauseTrouble(x),'restrictions expire')}
// Umbrella attaches, has no old Health or prevention activation, follows rotation.
{const g=fixture(),x=body(g,'P129',0,false);await play(g,'P149');eq(g.guard(x),5,'no Health boost');eq(g.absorb(x),1,'Rotated Absorb');await g.readyCharacter(x);eq(g.absorb(x),0,'Ready no umbrella Absorb');eq(g.items(x).length,1,'attachment');await g.remove(x,'hand');ok(!g.players[0].board.length&&g.players[0].discard.includes('P149'),'attachment cleanup')}
// Camera shows complete hand to controller and rotates, no opponent-trigger legacy.
{let seen;const g=fixture(r=>{if(r.title.startsWith('Security Camera:'))seen=r.options});g.players[1].hand=['P001','P024'];await play(g,'P147');const cam=g.players[0].board[0];await g.activate(cam.uid);eq(seen.length,2,'all cards shown');ok(seen[1].label.includes('Watch This'),'correct hand text');ok(!cam.ready,'Camera rotates')}
// Bylaws exactly one discard, including empty hand.
for(const n of [0,3]){const g=fixture();g.players[1].hand=Array(n).fill('P001');await play(g,'P083');eq(g.players[1].hand.length,Math.max(0,n-1),'single discard')}
// Action targets validated before cost, cancellation consumes nothing.
for(const id of ['P139','P140','P141','P143','LAB-HOA-004']){const g=fixture();g.players[0].hand=[id];ok(!g.canPlay(0),'no target '+id);const x=body(g,id==='LAB-HOA-004'?'P124':'P001',id==='LAB-HOA-004'?0:1,false);g.ask=async()=>null;const fuel=g.players[0].fuel;await g.play(0);eq(g.players[0].hand,[id],'cancel hand '+id);eq(g.players[0].fuel,fuel,'cancel fuel '+id);ok(g.obj(x.uid),'cancel target intact')}
{const g=fixture(),x=body(g,'P012',1);await play(g,'P139');eq(g.power(x),2,'Complaint -2');await g.pass();eq(g.power(x),2,'persists through opponent Turn');await g.pass();eq(g.power(x),4,'expires at start caster Turn')}
{const g=fixture(),x=body(g,'P124',1,false);await play(g,'P140');await step(g,1);ok(!x.ready,'stall step');await step(g,1);ok(x.ready,'only next step')}
{const g=fixture(),small=body(g,'P124',1),large=body(g,'P133',1);await play(g,'P141');ok(!g.obj(small.uid)&&g.obj(large.uid),'bounce limited');ok(g.players[1].hand.includes('P124'),'owner hand')}
{const g=fixture(),x=body(g,'P125',1,false),large=body(g,'P133',1,false);await play(g,'P143');ok(!g.obj(x.uid)&&g.obj(large.uid),'removal limited');ok(g.players[1].discard.includes('P125'),'Dismiss discard')}
// Peace and Quiet all three outcomes, recovery never undoes thresholds.
for(const mode of ['heal','pressure','draw']){const g=fixture();g.players[0].hp=9;g.players[0].breakingPointHit=true;if(mode!=='heal'){g.players[0].lastStraw=true;g.players[0].hp=0}if(mode==='draw'){g.players[1].lastStraw=true;g.players[1].hp=0}await play(g,'P144');eq(g.players[0].hp,mode==='heal'?12:0,'Peace no heal Last Straw');eq(g.players[1].hp,mode==='pressure'?17:mode==='draw'?0:20,'Peace pressure');eq(g.players[0].hand.length,mode==='draw'?1:0,'Peace Draw');ok(g.players[0].breakingPointHit,'BP remains spent')}
{const g=fixture(),x=body(g,'P124');body(g,'P001',1);body(g,'P001',1);await play(g,'P145');eq(g.absorb(x),1,'DigIn');eq(g.players[0].hand.length,1,'outnumber draw');await g.pass();eq(g.absorb(x),1,'through opponent Turn');await g.pass();eq(g.absorb(x),0,'expiry')}
{const g=fixture(),x=body(g,'P124');body(g,'P001',1,false);await play(g,'P146');eq(g.players[0].hand.length,2,'Draw2');ok(!g.canAttack(x)&&g.canCauseTrouble(x),'no attacks but Trouble allowed');await g.pass();await step(g,0);g.chars(1)[0].ready=false;ok(g.canAttack(x),'attack ban ends')}
{const g=fixture();g.players[0].attacked=true;g.players[0].hand=['P146'];ok(!g.canPlay(0),'cannot play after Attack')}
// Citizen gains for Action and Item, survives opponent cleanup, expires after owner Turn.
for(const id of ['P024','P028']){const g=fixture(),citizen=body(g,'P125'),x=body(g,'P001',1);g.turn=1;g.players[1].hand=[id];await g.play(0);eq(g.power(citizen),3,'Citizen trigger '+id);await g.pass();eq(g.power(citizen),3,'Citizen remains during own Turn');await g.pass();eq(g.power(citizen),2,'Citizen expires owner end')}
// Lawyer stacks and only charges opposing targeted Actions, not buffs or untargeted AoE.
{const g=fixture();body(g,'P137',1);body(g,'P137',1);body(g,'P001',1);g.players[0].hand=['P139'];g.players[0].fuel=2;ok(!g.canPlay(0),'stacked tax affordability');g.players[0].fuel=3;await g.play(0);eq(g.players[0].fuel,0,'two taxes paid');eq(g.lawyerTax(0,'P145'),0,'own aura no tax');eq(g.lawyerTax(0,'P022'),0,'untargeted AoE no tax');eq(g.lawyerTax(0,'LAB-FLM-005'),2,'Bottle Rockets taxed')}
// Neighbor only once opponent Turn; resets for next opponent Turn.
{const g=fixture(),n=body(g,'P130'),a=body(g,'P124',1),b=body(g,'P124',1);g.turn=1;await g.causeTrouble(a.uid);await g.causeTrouble(b.uid);eq(g.players[0].hand.length,1,'Neighbor once');await step(g,1);await g.causeTrouble(a.uid);eq(g.players[0].hand.length,2,'Neighbor resets')}
// Founder current state and Round8 stack; healing above10 toggles aura off.
{const g=fixture(),f=body(g,'LAB-HOA-003'),x=body(g,'P124');eq(g.trouble(x),2,'no BP aura');g.players[0].hp=10;eq(g.trouble(x),3,'BP aura');eq(g.trouble(f),3,'not self');g.round=8;eq(g.trouble(x),4,'Round8 stacks');g.players[0].hp=12;eq(g.trouble(x),3,'recovery toggles BP aura off');g.players[0].lastStraw=true;eq(g.trouble(x),4,'LastStraw aura')}
// HOA Final Warning source, no Defeat trigger, one time, bypassed on nonTrouble.
{const g=fixture(),a=body(g,'P004',1);g.turn=1;g.players[0].hp=11;await g.causeTrouble(a.uid);ok(!g.obj(a.uid),'Final Warning Dismiss source');ok(!g.players[1].defeatedRound,'not Defeat');eq(g.players[1].hand.length,1,'Boogie Dismiss Draw');const b=body(g,'P124',1);await g.causeTrouble(b.uid);ok(g.obj(b.uid),'BP only once')}
{const g=fixture(),a=body(g,'P124',1);g.players[0].hp=11;g.hurtLeader(0,1);await g.advance();ok(g.obj(a.uid),'no source no Dismiss')}
{const g=fixture(r=>r.title.startsWith('Final Warning:')?false:undefined),a=body(g,'P124',1);g.turn=1;g.players[0].hp=11;await g.causeTrouble(a.uid);ok(g.obj(a.uid),'may decline')}
// Florida Breaking Point every face visible, once, also no available targets.
for(let r=1;r<=6;r++){const g=fixture();satisfyDice(g,r);const a=body(g,'P001',1,true),b=body(g,'P012',1,false),c=body(g,'P017',1,false);g.players[1].hp=11;g.hurtLeader(1,1);await g.advance();eq(g.diceRolls[0].value,r,'visible BP '+r);ok(g.diceRolls[0].outcome,'outcome text');eq(a.ready,r!==1,'bad roll rotates');eq(b.ready,r!==1,'middle Readies');eq(c.ready,r===6,'six all');g.hurtLeader(1,1);await g.advance();eq(g.diceRolls.length,1,'once only')}
{const g=fixture();g.players[1].hp=11;g.hurtLeader(1,1);await g.advance();ok(g.players[1].breakingPointHit,'empty board still rolls')}
// Crossing both thresholds: BP resolution precedes LastStraw forced Turn end.
{const g=fixture(),a=body(g,'P133',1);g.turn=1;g.players[0].hp=11;a.troubleBonus=12;await g.causeTrouble(a.uid);ok(g.players[0].lastStraw&&!g.obj(a.uid),'Dismiss resolves on zero crossing');eq(g.turn,0,'Turn forced over');const log=g.log.slice().reverse();ok(log.findIndex(x=>x.includes('Final Warning dismisses'))<log.findIndex(x=>x.includes('reveals their Last Straw')),'BP before LastStraw')}
for(const id of hoa.audit_card_ids)ok(covered.has(id),'card exercised '+id);
console.log(`Stonewall regression passed: all ${covered.size} cards; ${checks} checks, both Breaking Points and all dice faces`);
// Full actual decks, both seats, conservation and progress; no balance claims.
for(let gameNo=0;gameNo<8;gameNo++){let g;g=new Game(pool,{decks:gameNo%2?[fl,hoa]:[hoa,fl]},r=>Promise.resolve(aiChoice(g,r)),()=>{},{firstPlayer:gameNo%2});g.begin();let steps=0;while(g.winner===null&&steps++<1600){const a=aiAction(g,g.turn),before=g.eventCount;if(a.type==='stash')g.stash(a.index);if(a.type==='play')await g.play(a.index);if(a.type==='attack')await g.attack(a.uid);if(a.type==='trouble')await g.causeTrouble(a.uid);if(a.type==='activate')await g.activate(a.uid);if(a.type==='pass')await g.pass();assert(g.eventCount!==before||g.winner!==null,'AI progress '+JSON.stringify(a));const count=g.players.reduce((n,s)=>n+s.deck.length+s.hand.length+s.discard.length+s.stash.length+s.board.reduce((n,x)=>n+1+(x.lower?1:0)+(x.cargo?.length||0)+(x.hidden?1:0),0),0);assert.equal(count,80,'card conservation')};if(g.winner===null){console.log(JSON.stringify({gameNo,round:g.round,players:g.players.map(s=>({hp:s.hp,lastStraw:s.lastStraw,hand:s.hand,board:s.board.map(x=>({id:x.id,ready:x.ready,noTrouble:x.noTrouble})),deck:s.deck.length})),log:g.log.slice(0,8)}));assert.fail('game completes')}}
console.log('Stonewall / Reckless eight-game integration passed (functionality, not balance).');
